### ISSUE TITLE
setup.py raises ImportError: No module named bs4

### ISSUE THREAD

**Issue by mete0r** [HallaZzang/pyneis#1]
virtualenv 환경에서

```
pip install pyneis
```

로 설치하면

```
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "pyneis/setup.py", line 5, in <module>
    from neis import __version__, __author__, __author_email__
  File "neis/__init__.py", line 9, in <module>
    from .client import Client
  File "neis/client.py", line 5, in <module>
    from .school import School
  File "neis/school.py", line 7, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4
```

라며 실패합니다.

**Comment by hallazzang** [comment]
setup.py에서 setup의 인자로 install_requires에 BeautifulSoup4를 넣어줬는데도 이런 에러가 나나보네요. 제가 아직 setup 스크립트랑 패키지 배포에 미숙한 점 양해 바랍니다 (_ _)
virtualenv에서 pip install beautifulsoup4 를 하시면 해결될겁니다.

**Comment by mete0r** [comment]
(pip가 패키지를 다운받은 후, 혹은 소스를 직접 다운받아) 설치를 위해 setup.py를 실행할 때,  setup.py가 version, author 등의 값을 얻기 위해 neis를 임포트하면서, neis.client →  neis.school → bs4가 차례로 함께 임포트되기 때문에 그렇습니다. 아직 setup.py가 install_requires 값을 setup()에 넘기기도 전이지요.

저도 패키징 때문에 애를 먹은 경험이 있어서 남겨보았습니다.

**Comment by hallazzang** [comment]
각 소스코드에서 import neis만 해두고 이후에 neis.school.School로 접근하거나 setup.py에서 파일 입력으로 version, author 등의 정보들을 받아와야 하겠군요. 조언 감사합니다. 반영하겠습니다.

**Comment by hallazzang** [comment]
setup.py를 수정했습니다.
